name: Build and deploy on GitHub Pages

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Export Website
        run: npm run export
      - name: Deploy GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: crazy-max/ghaction-github-pages@1510b11c0c2f843eafb8ff41b3da8c467c8d4a9f
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          # Git branch where assets will be deployed
          target_branch: gh-pages
          # Create incremental commit instead of doing push force
          keep_history: true
          # Allow an empty commit to be created
          allow_empty_commit: true
          # Build directory to deploy
          build_dir: out
          # The committer name and email address
          committer: leon@machens.koeln
          # The author name and email address
          author: Leon Machens
          # Commit message
          commit_message: 🚀 Deploy on GitHub pages
